### ISSUE TITLE
sampling image 

### ISSUE THREAD

**Issue by betterze** [genforce/trgan#1]
Dear Genforce group, 

Thank you for sharing the great work with us, I really like it. 

Would you mind clarifying how the model sampling new image from generator? According to the paper, a generated image G(z,t) requires random noise code 'z' and transformation code 't'. We can sample 'z' easily, but how to sample 't'? 

Thank you for your understanding.

Best Wishes,

Alex

**Comment by kaiwenzha** [comment]
Hi Alex,

Thanks for your note. Please refer to the implementation details in Section 4.1 of the paper. The layer-wise transformation code t_k is a 4-D vector, sampled from a uniform distribution U(-1, 1), and latent code z_k is a 32-D vector, sampled from a normal distribution N(0, 1).

**Comment by betterze** [comment]
Sorry for missing that in the paper. Thank you for your help.
